# Generated by Django 4.2.7 on 2023-11-11 02:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogCategoryTable',
            fields=[
                ('cate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cate_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='blogPostTable',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.TextField(blank=True, null=True)),
                ('git_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('other_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('post_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategorytable')),
            ],
        ),
        migrations.CreateModel(
            name='blogCommentTable',
            fields=[
                ('email', models.EmailField(max_length=1000)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposttable')),
            ],
        ),
    ]
