# Generated by Django 4.2.6 on 2023-12-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposttable_adds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogposttable',
            options={'ordering': ['-created']},
        ),
    ]
